/*
The MIT License (MIT)

Copyright (c) Terry Evans Vaughn 

All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
 */

package com.blueseer.eng;

import bsmf.MainFrame;
import java.awt.Color;
import java.awt.Component;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.miginfocom.swing.MigLayout;
import static bsmf.MainFrame.checkperms;
import static bsmf.MainFrame.db;
import static bsmf.MainFrame.ds;
import static bsmf.MainFrame.menumap;
import static bsmf.MainFrame.panelmap;
import static bsmf.MainFrame.pass;
import static bsmf.MainFrame.reinitpanels;
import static bsmf.MainFrame.url;
import static bsmf.MainFrame.user;
import java.sql.Connection;

/**
 *
 * @author vaughnte
 */
public class OVDevBrowse extends javax.swing.JPanel {

    
       class MyTableModel extends DefaultTableModel {  
  
    public MyTableModel(Object rowData[][], Object columnNames[]) {  
         super(rowData, columnNames);  
      }  
     
    @Override  
      public Class getColumnClass(int col) {  
        if (col == 0)       //second column accepts only Integer values  
            return Integer.class;  
        else return String.class;  //other columns accept String values  
    }  
  
    @Override  
      public boolean isCellEditable(int row, int col) {  
        if (col == 0)       //first column will be uneditable  
            return false;  
        else return true;  
      }  
    }    
        
        
        class SomeRenderer extends DefaultTableCellRenderer {
        
    public Component getTableCellRendererComponent(JTable table,
            Object value, boolean isSelected, boolean hasFocus, int row,
            int column) {

        Component c = super.getTableCellRendererComponent(table,
                value, isSelected, hasFocus, row, column);

       
            if (column == 0)
            c.setForeground(Color.BLUE);
            else
                c.setBackground(table.getBackground());
       
        return c;
    }
    }
    
    
    
    
    /**
     * Creates new form CustXrefRpt1
     */
    public OVDevBrowse() {
        initComponents();
    }

    
      public void initvars(String[] arg) {
       rbactive.setSelected(true);
       rbinactive.setSelected(false);
       buttonGroup1.add(rbactive);
       buttonGroup1.add(rbinactive);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tbtext = new javax.swing.JTextField();
        rbactive = new javax.swing.JRadioButton();
        rbinactive = new javax.swing.JRadioButton();
        btview = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pgloading = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablereport = new javax.swing.JTable();

        jLabel2.setText("Text Search:");

        tbtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtextActionPerformed(evt);
            }
        });

        rbactive.setText("Active");

        rbinactive.setText("Inactive");

        btview.setText("View");
        btview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btviewActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 9));
        jLabel1.setText("Enter first couple of chars:");

        pgloading.setIndeterminate(true);
        pgloading.setVisible(false);

        // Migrated from javax.swing.GroupLayout to MigLayout (see the "Layout"
        // section in README): a single row, baseline-aligned, that reflows
        // sanely instead of relying on fixed pixel gaps.
        jPanel1.setLayout(new MigLayout("insets 5 23 5 5", "[]18[]3[]18[]5[]5[]5[]", "[]"));
        jPanel1.add(jLabel1);
        jPanel1.add(jLabel2);
        jPanel1.add(tbtext, "width 80!");
        jPanel1.add(rbactive);
        jPanel1.add(rbinactive);
        jPanel1.add(btview);
        jPanel1.add(pgloading, "width 80!, wrap");

        tablereport.setAutoCreateRowSorter(true);
        tablereport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablereport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablereportMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablereport);

        // Migrated from javax.swing.GroupLayout to MigLayout: the toolbar row
        // keeps its natural height, the table grows to fill whatever space is
        // left, and both reflow properly on resize/HiDPI instead of relying on
        // a fixed "356" pixel table height.
        this.setLayout(new MigLayout("fill, insets 11 0 0 0", "[grow]", "[]related[grow]"));
        this.add(jPanel1, "growx, wrap");
        this.add(jScrollPane1, "grow");
    }// </editor-fold>//GEN-END:initComponents

    private void btviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btviewActionPerformed

        if (rbactive.isSelected() && rbinactive.isSelected()) {
            bsmf.MainFrame.show("Select either active OR inactive...not both");
            return;
        }

        // Runs the query on a background thread instead of the EDT (see the
        // "Asynchronous Database Calls" section in README) so the UI doesn't
        // freeze while this executes; pgloading gives the user a visual cue
        // that something is happening in the meantime.
        final boolean active = rbactive.isSelected();
        final String search = tbtext.getText();
        btview.setEnabled(false);
        pgloading.setVisible(true);

        new SwingWorker<javax.swing.table.DefaultTableModel, Void>() {
            @Override
            protected javax.swing.table.DefaultTableModel doInBackground() throws Exception {
                javax.swing.table.DefaultTableModel mymodel = new javax.swing.table.DefaultTableModel(new Object[][]{},
                    new String[]{"ID", "Title", "Status", "NoteDate", "Notes"});

                Connection con = (ds != null) ? ds.getConnection() : DriverManager.getConnection(url + db, user, pass);
                try {
                    String sql = "SELECT ovdm_id, ovdm_title, ovdm_status, ovdd_date, ovdd_note FROM ov_devm "
                        + "left outer join ov_devd on ovdd_parent = ovdm_id where ovdm_status = ? and ovdm_title like ?";
                    try (PreparedStatement ps = con.prepareStatement(sql)) {
                        ps.setString(1, active ? "open" : "closed");
                        ps.setString(2, "%" + search + "%");
                        try (ResultSet res = ps.executeQuery()) {
                            while (res.next()) {
                                mymodel.addRow(new Object[]{res.getString("ovdm_id"),
                                    res.getString("ovdm_title"),
                                    res.getString("ovdm_status"),
                                    res.getString("ovdd_date"),
                                    res.getString("ovdd_note")
                                });
                            }
                        }
                    }
                } finally {
                    con.close();
                }
                return mymodel;
            }

            @Override
            protected void done() {
                btview.setEnabled(true);
                pgloading.setVisible(false);
                try {
                    javax.swing.table.DefaultTableModel mymodel = get();
                    tablereport.setModel(mymodel);
                    tablereport.getColumnModel().getColumn(0).setCellRenderer(new OVDevBrowse.SomeRenderer());
                } catch (Exception e) {
                    MainFrame.bslog(e);
                    bsmf.MainFrame.show("Sql code does not execute");
                }
            }
        }.execute();
    }//GEN-LAST:event_btviewActionPerformed

    private void tbtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtextActionPerformed

    private void tablereportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablereportMouseClicked
       int row = tablereport.rowAtPoint(evt.getPoint());
        int col = tablereport.columnAtPoint(evt.getPoint());
        if ( col == 0) {
              if (! checkperms("DevLog")) { return; }
                reinitpanels("DevLog", true, new String[]{tablereport.getValueAt(row, col).toString()});
           
        }
    }//GEN-LAST:event_tablereportMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btview;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar pgloading;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbactive;
    private javax.swing.JRadioButton rbinactive;
    private javax.swing.JTable tablereport;
    private javax.swing.JTextField tbtext;
    // End of variables declaration//GEN-END:variables
}
